### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Flat** [ChineseCartoonists/safepomf#1]
## Basic Requirements

- [ ] HTML page that is served when a user visits the index page
- [ ] Configuration file parsing
    - [ ] Enabled/Disabled File Types
    - [ ] Max File Size
    - [ ] Authenticated Users Only
- [ ] Administrator Panel
    - [ ] Ability to delete specific files
    - [ ] Ability to delete files by checksum
    - [ ] Ability to create/delete user accounts
    - [ ] Ability to disable/enable user accounts
    - [ ] Audit log
- [ ] API for 3rd Party Tools
    - [ ] Support for Authentication Tokens

## Extended Requirements

- [ ] Customizable Themes
- [ ] Custom Mascots
- [ ] Groovy Annoying Music That Autoplays
